In [76]:
import numpy as np
from math import exp
from math import log
np.random.seed(1)
def logistic_function(a,W):
    b=a.dot(W)
    return 1/(1+np.exp(b))
def linear_function(a,W):
    return a.dot(W)
def loss(x,inp):
    output=0
    for i in range(len(x)):
        output-=(inp[i]*log(x[i])+(1-inp[i])*log(1-x[i]))
    return output
def der_loss(x,inp):
    output=[]
    for i in range(len(x)):
        output.append(-(inp[i]/x[i])+(1-inp[i])/(2-x[i]))
    return output
import numpy as np
input=np.array([0,1,1,0,1])
weight_0_1=np.random.randn(5,3)
weight_1_2=np.random.randn(3,5)
for epoch in range(60):
    output_1=linear_function(input,weight_0_1)
    output_2=logistic_function(output_1,weight_1_2)
    loss_1=loss(output_2,input)
    delta_2=

In [80]:
import numpy as np
np.random.seed(1)

# Vectorized sigmoid
def logistic_function(a, W):
    return 1 / (1 + np.exp(-a.dot(W)))

# Linear activation
def linear_function(a, W):
    return a.dot(W)

# Binary cross-entropy loss
def loss(x, inp):
    x = np.clip(x, 1e-15, 1 - 1e-15)  # Avoid log(0)
    return -np.mean(inp * np.log(x) + (1 - inp) * np.log(1 - x))

# Derivative of loss
def der_loss(x, inp):
    x = np.clip(x, 1e-15, 1 - 1e-15)
    return -(inp / x - (1 - inp) / (1 - x))

alpha = 0.2
input_data = np.array([0, 1, 1, 0, 1])  # Shape (5,)
weight_0_1 = np.random.randn(5, 3)      # Shape (5, 3)
weight_1_2 = np.random.randn(3, 5)      # Shape (3, 5)

for epoch in range(60):
    # Forward pass
    output_1 = linear_function(input_data, weight_0_1)  # Shape (3,)
    output_2 = logistic_function(output_1, weight_1_2)  # Shape (5,)
    
    # Loss
    loss_1 = loss(output_2, input_data)
    
    # Gradients
    delta_2 = der_loss(output_2, input_data)  # Shape (5,)
    grad_weight_1_2 = np.outer(output_1, delta_2)  # Shape (3, 5)
    delta_1 = delta_2.dot(weight_1_2.T)  # Shape (3,)
    grad_weight_0_1 = np.outer(input_data, delta_1)  # Shape (5, 3)
    
    # Batch GD: Single update per epoch
    weight_1_2 -= alpha * grad_weight_1_2
    weight_0_1 -= alpha * grad_weight_0_1
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss_1}")

print("Final output:", output_2)
print(weight_0_1)
print(weight_1_2)

Epoch 0, Loss: 0.8236424541417632
Epoch 10, Loss: 9.992007221626415e-16
Epoch 20, Loss: 9.992007221626415e-16
Epoch 30, Loss: 9.992007221626415e-16
Epoch 40, Loss: 9.992007221626415e-16
Epoch 50, Loss: 9.992007221626415e-16
Final output: [0. 1. 1. 0. 1.]
[[ 1.62434536e+00 -6.11756414e-01 -5.28171752e-01]
 [ 5.11752295e+14  9.03080777e+14 -1.02396892e+14]
 [ 5.11752295e+14  9.03080777e+14 -1.02396892e+14]
 [-2.49370375e-01  1.46210794e+00 -2.06014071e+00]
 [ 5.11752295e+14  9.03080777e+14 -1.02396892e+14]]
[[-3.96401623e+14  3.96401623e+14  3.96401623e+14 -3.96401623e+14
   3.96401623e+14]
 [-6.99523362e+14  6.99523362e+14  6.99523362e+14 -6.99523362e+14
   6.99523362e+14]
 [ 7.93162915e+13 -7.93162915e+13 -7.93162915e+13  7.93162915e+13
  -7.93162915e+13]]


C:\Users\adity\AppData\Local\Temp\ipykernel_11672\2996363514.py:6: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-a.dot(W)))


In [136]:
import numpy as np
np.random.seed(1)
data=np.array([1,2,3,4,5])
weight_0_1=np.random.randn(5,3)
weight_1_2=np.random.randn(3,5)
for epoch in range(60):
    layer_1=data.dot(weight_0_1)
    layer_2=layer_1.dot(weight_1_2)
    delta_2=2*(layer_2-data)/5
    grad_2=np.outer(layer_1,delta_2)
    
    weight_1_2-=0.01*grad_2
    delta_1=delta_2.dot(weight_1_2.T)        
    grad_1=np.outer(data,delta_1)
    weight_0_1-=0.01*grad_1
print(layer_2)

[0.99999998 1.99999998 3.00000001 4.00000003 4.99999998]


In [112]:
import numpy as np
np.random.seed(1)

# Linear activation (identity)
def linear_function(a, W):
    return a.dot(W)

# Mean squared error loss
def mse_loss(pred, true):
    return np.mean((pred - true) ** 2)

alpha = 0.01  # Learning rate
data = np.array([1, 2, 3, 4, 5])  # Shape (5,)
weight_0_1 = np.random.randn(5, 3)  # Shape (5, 3)
weight_1_2 = np.random.randn(3, 5)  # Shape (3, 5)

for epoch in range(60):
    # Forward pass
    layer_1 = linear_function(data, weight_0_1)  # Shape (3,)
    layer_2 = linear_function(layer_1, weight_1_2)  # Shape (5,)
    
    # Loss
    loss = mse_loss(layer_2, data)
    
    # Gradients
    delta_2 = 2 * (layer_2 - data) / len(data)  # Shape (5,)
    grad_weight_1_2 = np.outer(layer_1, delta_2)  # Shape (3, 5)
    delta_1 = delta_2.dot(weight_1_2.T)  # Shape (3,)
    grad_weight_0_1 = np.outer(data, delta_1)  # Shape (5, 3)
    
    # Batch GD: Single update per epoch
    weight_1_2 -= alpha * grad_weight_1_2
    weight_0_1 -= alpha * grad_weight_0_1
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

print("Final weight_0_1:\n", weight_0_1)
print("Final weight_1_2:\n", weight_1_2)
print("Final output:", layer_2)

Epoch 0, Loss: 9.102275669731629
Epoch 10, Loss: 0.027486968014934655
Epoch 20, Loss: 4.573334757377309e-05
Epoch 30, Loss: 1.3915039667685855e-07
Epoch 40, Loss: 4.960333410897945e-10
Epoch 50, Loss: 1.8044274394472322e-12
Final weight_0_1:
 [[ 1.65351765 -0.62264862 -0.52440159]
 [-1.01462406  0.84362321 -2.29399838]
 [ 1.83232861 -0.79388353  0.33034957]
 [-0.13268124  1.4185391  -2.04506007]
 [-0.17655579 -0.4385154   1.15262024]]
Final weight_1_2:
 [[-0.93291789 -0.20163456 -0.96415419  0.0973619   0.81391902]
 [-0.97986837  1.11612301  0.82286257  0.54394741  1.08144821]
 [-1.0063455  -0.0507354  -0.73315661 -0.37648115  0.05484951]]
Final output: [0.9999999  1.99999989 3.00000005 4.00000016 4.9999999 ]


In [128]:
import numpy as np
np.random.seed(1)

data = np.array([1, 2, 3, 4, 5])
weight_0_1 = np.random.randn(5, 3)
weight_1_2 = np.random.randn(3, 5)

for epoch in range(60):
    # Forward pass
    layer_1 = data.dot(weight_0_1)  # Shape (3,)
    layer_2 = layer_1.dot(weight_1_2)  # Shape (5,)
    
    # Loss
    loss = np.mean((layer_2 - data) ** 2)  # Scalar MSE
    
    # Gradients
    delta_2 = 2 * (layer_2 - data) / len(data)  # Shape (5,)
    grad_2 = np.outer(layer_1, delta_2)  # Shape (3, 5)
    weight_1_2 -= 0.2 * grad_2
    delta_1 = delta_2.dot(weight_1_2.T)  # Shape (3,)
    grad_1 = np.outer(data, delta_1)  # Shape (5, 3)
    weight_0_1 -= 0.2 * grad_1
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

print("weight_0_1:\n", weight_0_1)
print("weight_1_2:\n", weight_1_2)
print(layer_2)

Epoch 0, Loss: 9.102275669731629
Epoch 10, Loss: nan
Epoch 20, Loss: nan
Epoch 30, Loss: nan
Epoch 40, Loss: nan
Epoch 50, Loss: nan
weight_0_1:
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]]
weight_1_2:
 [[nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]
[nan nan nan nan nan]


C:\Users\adity\AppData\Local\Temp\ipykernel_11672\3255158237.py:14: RuntimeWarning: overflow encountered in square
  loss = np.mean((layer_2 - data) ** 2)  # Scalar MSE
C:\Users\adity\AppData\Local\Temp\ipykernel_11672\3255158237.py:19: RuntimeWarning: invalid value encountered in subtract
  weight_1_2 -= 0.2 * grad_2


In [130]:
import numpy as np
np.random.seed(1)

# Normalize input to [0, 1]
data = np.array([1, 2, 3, 4, 5]) / 5.0  # Shape (5,)
weight_0_1 = np.random.randn(5, 3)       # Shape (5, 3)
weight_1_2 = np.random.randn(3, 5)       # Shape (3, 5)

for epoch in range(60):
    # Forward pass
    layer_1 = data.dot(weight_0_1)  # Shape (3,)
    layer_2 = layer_1.dot(weight_1_2)  # Shape (5,)
    
    # Loss
    loss = np.mean((layer_2 - data) ** 2)
    
    # Gradients with clipping
    delta_2 = 2 * (layer_2 - data) / len(data)  # Shape (5,)
    delta_2 = np.clip(delta_2, -1, 1)  # Clip to prevent explosion
    grad_2 = np.outer(layer_1, delta_2)  # Shape (3, 5)
    weight_1_2 -= 0.01 * grad_2  # Smaller learning rate
    delta_1 = delta_2.dot(weight_1_2.T)  # Shape (3,)
    delta_1 = np.clip(delta_1, -1, 1)  # Clip
    grad_1 = np.outer(data, delta_1)  # Shape (5, 3)
    weight_0_1 -= 0.01 * grad_1
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

print("weight_0_1:\n", weight_0_1)
print("weight_1_2:\n", weight_1_2)
print("Final output:", layer_2)

Epoch 0, Loss: 0.3640910267892653
Epoch 10, Loss: 0.25748149297317025
Epoch 20, Loss: 0.19798629931670925
Epoch 30, Loss: 0.15985627169698144
Epoch 40, Loss: 0.13245385520523345
Epoch 50, Loss: 0.11108450083237069
weight_0_1:
 [[ 1.64315443 -0.62124459 -0.5137946 ]
 [-1.03535049  0.84643128 -2.2727844 ]
 [ 1.80123897 -0.78967142  0.36217054]
 [-0.17413411  1.42415525 -2.00263211]
 [-0.22837187 -0.43149522  1.20565519]]
weight_1_2:
 [[-1.04629771 -0.19257724 -0.92631303  0.06418301  0.67489695]
 [-1.05412375  1.12585047  0.8561924   0.52157353  0.98337037]
 [-0.80235204 -0.0752656  -0.82121302 -0.31655597  0.32082793]]
Final output: [-0.17582035  0.47486327  0.78353297  0.6499968   0.47766882]
