In [7]:
import numpy as np
#vectors
v=np.array([1,2,1])
w=np.array([2,5,2])
print(v+w)
print(v-w)
print(v*w)
print(np.dot(v,w))
#to find the length of any vector we use
print(np.linalg.norm(v))#linalglinear algebra

[3 7 3]
[-1 -3 -1]
[ 2 10  2]
14
2.449489742783178


In [19]:
#matrix calculations
v=np.array([[1,2],[4,5]])
print(v)
#to find the inverse use this
print(np.linalg.inv(v))

[[1 2]
 [4 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [1]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
values,vectors=np.linalg.eig(A)
print(values)
print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [25]:
#to find the single value decomposition of any matrix
import numpy as np
a=np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])
u,s,v=np.linalg.svd(a)
print(u)
print(v)
print(s)
#np.linalg.svd returns the singular value in case of s and not the sigma matrix to get the sigma matrix we have to make a zeros matrix of same size as a and fill the diagonal values with the singular values
b=np.zeros((3,4))
c=np.diag(s)
b[:,:-1]=c
print(b)

[[ 0.81094933 -0.09338945  0.57761543]
 [ 0.56996499  0.34927886 -0.74373664]
 [ 0.13229171 -0.93235331 -0.33647618]]
[[ 2.04551323e-01  3.44271217e-01  5.48822541e-01  7.33777830e-01]
 [ 2.18067510e-01 -6.56064669e-01 -4.37997159e-01  5.74616568e-01]
 [-7.59784169e-01  3.43108067e-01 -4.16676102e-01  3.62471925e-01]
 [-5.77350269e-01 -5.77350269e-01  5.77350269e-01  5.39416626e-16]]
[6.75094297 1.17344125 0.21864263]
[[6.75094297 0.         0.         0.        ]
 [0.         1.17344125 0.         0.        ]
 [0.         0.         0.21864263 0.        ]]
