In [14]:
import numpy as np
rng=np.random.default_rng(1303)
a=rng.normal(size=50)
b=a+rng.normal(loc=50,scale=1,size=50)
print(np.corrcoef(a,b))

[[1.         0.66802777]
 [0.66802777 1.        ]]


In [14]:
import numpy as np
a=np.array([1,2,3,4,5])
a=np.where(a<4,10,0)
print(a)

[10 10 10  0  0]


In [8]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np